@startuml db
hide circle

entity "DimShopJ" as shop{
    shop_id : number
    --
    *name_fr : text
    *name_en : text
    *surface : int
    is_online: bool
    --
    id : shop_id
}

' entity "DimWebshop" as wshop{
'     wshop_id : number <<generated>>
'     --
'     *url : text
' }

entity "DimEmployeeJ" as emp {
    emp_id : number
    --
    *first_name : text
    *last_name : text
    *street : text
    *birth_date : date
    --
    id : emp_id
}


entity "DimClient" as clt {
	clt_id : number
--
    *company_name : text
    contact_name : text
    contact_title : text

--
    id : clt_id
}
entity "DimShipperJ" as shp{
    ship_id : number
    --
    *company_name : text
    *phone : text
    --
    id : ship_id
}

entity "DimProductJ" as prod {
    prod_id : number
    --
    *name_fr : text
    *name_en : text
    *quantityPerUnit : text
    *unitPrice : number
    *cat_id : number
    *name_cat_fr : text
    *name_cat_en : text
    --
    id : prod_id
}
entity "FactCommand" as cmd{
    cmd_id : number
    --
    *price : number
    *product_key : number
    *freight : number
    *shipper_key : number
    *ship_adress_key : number
    *shop_key : number
    *shop_adress_key : number
    *employee_key : number
    *client_key : number
    *order_date_key : number
    *required_date_key : number
    *shipped_date_key : number
    --
    id : cmd_id
    ref : product_key
    ref : order_date_key
    ref : required_date_key
    ref : shipped_date_key
    ref : shipper_key
    ref : shop_key
}
entity "DimAdress" as adr{
    adr_id : number
    --
    *locality : text
    *code : number
    *country_id
    *country_name_fr : text
    *country_name_en : text
    --
    id : adr_id
}

entity "DimDate" as date {
    date_key : number
    --
    *date : date
    *day_of_week : number
    *day_of_week_name_fr : text
    *day_of_week_name_en : text
    *week_of_year : number
    *month : number
    *month_name_fr : text
    *month_name_en : text
    *year : number
    --
    id : date_key
}



' prod <-- cmd
' emp <-- cmd
' clt <-- cmd
' shp <-- cmd
' shop <-- cmd
' ' wshop <-- cmd
' adr <-- cmd
' ctr <-- cmd
' dat <-- cmd

cmd::order_date_key --> date::date_key
cmd::required_date_key --> date::date_key
cmd::shipped_date_key --> date::date_key
cmd::product_key -up-> prod::prod_id
cmd::employee_key  -left-> emp::emp_id
cmd::shop_key -left-> shop::shop_id
cmd::shipper_key -left-> shp::ship_id
cmd::shop_adress_key -right-> adr::adr_id
cmd::ship_adress_key --> adr::adr_id
cmd::client_key -right-> clt::clt_id

@endum