USE [ProjetETLBI]
GO

/****** Object:  Table [dbo].[DimShipper]    Script Date: 09-12-21 19:19:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DimShipper](
	[Id] [numeric](18, 0) NOT NULL,
	[CompanyName] [nchar](40) NOT NULL,
	[Phone] [nchar](24) NOT NULL,
 CONSTRAINT [PK_DimShipper] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


